services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: takeaway_drinks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data: